# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v3
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2.0.0

      - name: Restore Packages
        run: nuget restore

      - name: Build Solution
        run: msbuild.exe /p:platform="x64" /p:configuration="Release"
        
      # 🔽 NEW: find "obj\CM Tracker.zip", copy/rename to dist/CM.Tracker.bhm
      - name: Package .bhm
        shell: pwsh
        run: |
          # Find the first match of 'CM Tracker.zip' under any obj\ folder
          $zip = Get-ChildItem -Path "$env:GITHUB_WORKSPACE" -Filter "CM Tracker.zip" -Recurse |
                 Where-Object { $_.FullName -match "\\obj\\" } |
                 Select-Object -First 1

          if (-not $zip) {
            Write-Error "Could not find 'CM Tracker.zip' under any 'obj\' folder."
            exit 1
          }

          New-Item -ItemType Directory -Path "$env:GITHUB_WORKSPACE\dist" -Force | Out-Null
          $bhm = Join-Path "$env:GITHUB_WORKSPACE\dist" "CM.Tracker.bhm"

          Copy-Item $zip.FullName $bhm -Force

          Write-Host "Packaged: $bhm"

      # 🔽 NEW: upload artifact so you can download it from the Actions run
      - name: Upload .bhm artifact
        uses: actions/upload-artifact@v4
        with:
          name: CM.Tracker.bhm
          path: dist/CM.Tracker.bhm
          if-no-files-found: error
