# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v3
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2.0.0

      - name: Restore Packages
        run: nuget restore

      - name: Build Solution
        run: msbuild.exe /p:platform="x64" /p:configuration="Release"
        

      # 🔽 NEW: upload artifact so you can download it from the Actions run
      - name: Upload .zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: CM.Tracker.zip
          path: obj/CM Tracker.zip
          if-no-files-found: error
